name: food4good_app
description: Food4Good Mobile Application

version: 1.0.1+2

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  badges: ^1.1.1
  bottom_navigation_badge: ^1.0.3
  cached_network_image: ^2.2.0+1
  cupertino_icons: ^0.1.3
  device_info: ^0.4.2+4
  enum_to_string: ^1.0.9
  firebase_crashlytics: 0.1.3+3
  firebase_messaging: ^6.0.16
  flutter_cupertino_localizations: ^1.0.1
  flutter_launcher_icons: ^0.7.5
  flutter_spinkit: ^4.1.2+1
  font_awesome_flutter: ^8.8.1
  geolocation: ^1.1.2
  http: ^0.12.1
  image_picker: ^0.6.7+1
  location: ^3.0.2
  pdf_viewer_plugin: ^1.0.0+2
  package_info: ^0.4.1
  slider_button: ^0.5.0
  sprintf: ^4.0.2
  passwordfield: ^0.0.6
  provider: ^4.1.3
  shared_preferences: ^0.5.7+3
  url_launcher: ^5.4.10
  url_launcher_macos: ^0.0.1+7
  url_launcher_platform_interface: ^1.0.7
  url_launcher_web: ^0.1.1+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf

firebase_core:

firebase_messaging: //
module:
  androidX: true